services:
    abenmada_broken_link_handler_plugin.listener.product:
        class: Abenmada\BrokenLinkHandlerPlugin\EventListener\ProductListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: sylius.product.pre_create, method: preCreate }
            - { name: kernel.event_listener, event: sylius.product.pre_update, method: preUpdate }

    abenmada_broken_link_handler_plugin.listener.taxon:
        class: Abenmada\BrokenLinkHandlerPlugin\EventListener\TaxonListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: sylius.taxon.pre_create, method: preCreate }
            - { name: kernel.event_listener, event: sylius.taxon.pre_update, method: preUpdate }

    abenmada_broken_link_handler_plugin.listener.exception_404:
        class: Abenmada\BrokenLinkHandlerPlugin\EventListener\Exception404Listener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
