services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

imports:
    - { resource: "packages/resource.yaml" }
    - { resource: "packages/event.yaml" }
    - { resource: "packages/factory.yaml" }
    - { resource: "packages/menu.yaml" }
